//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.14 at 02:13:19 AM BST 
//


package uk.gemwire.bolblox.format.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}X"/>
 *         &lt;element ref="{}Y"/>
 *         &lt;element ref="{}Z"/>
 *         &lt;element ref="{}R00"/>
 *         &lt;element ref="{}R01"/>
 *         &lt;element ref="{}R02"/>
 *         &lt;element ref="{}R10"/>
 *         &lt;element ref="{}R11"/>
 *         &lt;element ref="{}R12"/>
 *         &lt;element ref="{}R20"/>
 *         &lt;element ref="{}R21"/>
 *         &lt;element ref="{}R22"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "x",
    "y",
    "z",
    "r00",
    "r01",
    "r02",
    "r10",
    "r11",
    "r12",
    "r20",
    "r21",
    "r22"
})
@XmlRootElement(name = "CFrame")
public class CFrame {

    @XmlElement(name = "X")
    protected double x;
    @XmlElement(name = "Y")
    protected double y;
    @XmlElement(name = "Z")
    protected double z;
    @XmlElement(name = "R00")
    protected double r00;
    @XmlElement(name = "R01")
    protected double r01;
    @XmlElement(name = "R02")
    protected double r02;
    @XmlElement(name = "R10")
    protected double r10;
    @XmlElement(name = "R11")
    protected double r11;
    @XmlElement(name = "R12")
    protected double r12;
    @XmlElement(name = "R20")
    protected double r20;
    @XmlElement(name = "R21")
    protected double r21;
    @XmlElement(name = "R22")
    protected double r22;

    /**
     * Gets the value of the x property.
     * 
     */
    public double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     */
    public double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     */
    public void setY(double value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     * 
     */
    public double getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     */
    public void setZ(double value) {
        this.z = value;
    }

    /**
     * Gets the value of the r00 property.
     * 
     */
    public double getR00() {
        return r00;
    }

    /**
     * Sets the value of the r00 property.
     * 
     */
    public void setR00(double value) {
        this.r00 = value;
    }

    /**
     * Gets the value of the r01 property.
     * 
     */
    public double getR01() {
        return r01;
    }

    /**
     * Sets the value of the r01 property.
     * 
     */
    public void setR01(double value) {
        this.r01 = value;
    }

    /**
     * Gets the value of the r02 property.
     * 
     */
    public double getR02() {
        return r02;
    }

    /**
     * Sets the value of the r02 property.
     * 
     */
    public void setR02(double value) {
        this.r02 = value;
    }

    /**
     * Gets the value of the r10 property.
     * 
     */
    public double getR10() {
        return r10;
    }

    /**
     * Sets the value of the r10 property.
     * 
     */
    public void setR10(double value) {
        this.r10 = value;
    }

    /**
     * Gets the value of the r11 property.
     * 
     */
    public double getR11() {
        return r11;
    }

    /**
     * Sets the value of the r11 property.
     * 
     */
    public void setR11(double value) {
        this.r11 = value;
    }

    /**
     * Gets the value of the r12 property.
     * 
     */
    public double getR12() {
        return r12;
    }

    /**
     * Sets the value of the r12 property.
     * 
     */
    public void setR12(double value) {
        this.r12 = value;
    }

    /**
     * Gets the value of the r20 property.
     * 
     */
    public double getR20() {
        return r20;
    }

    /**
     * Sets the value of the r20 property.
     * 
     */
    public void setR20(double value) {
        this.r20 = value;
    }

    /**
     * Gets the value of the r21 property.
     * 
     */
    public double getR21() {
        return r21;
    }

    /**
     * Sets the value of the r21 property.
     * 
     */
    public void setR21(double value) {
        this.r21 = value;
    }

    /**
     * Gets the value of the r22 property.
     * 
     */
    public double getR22() {
        return r22;
    }

    /**
     * Sets the value of the r22 property.
     * 
     */
    public void setR22(double value) {
        this.r22 = value;
    }

}
