//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.14 at 02:13:19 AM BST 
//


package uk.gemwire.bolblox.format.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gemwire.bolblox.format.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _B_QNAME = new QName("", "B");
    private final static QName _CustomPhysics_QNAME = new QName("", "CustomPhysics");
    private final static QName _G_QNAME = new QName("", "G");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _Weight_QNAME = new QName("", "Weight");
    private final static QName _R10_QNAME = new QName("", "R10");
    private final static QName _R21_QNAME = new QName("", "R21");
    private final static QName _R20_QNAME = new QName("", "R20");
    private final static QName _R01_QNAME = new QName("", "R01");
    private final static QName _R12_QNAME = new QName("", "R12");
    private final static QName _R_QNAME = new QName("", "R");
    private final static QName _R00_QNAME = new QName("", "R00");
    private final static QName _R11_QNAME = new QName("", "R11");
    private final static QName _R22_QNAME = new QName("", "R22");
    private final static QName _R02_QNAME = new QName("", "R02");
    private final static QName _YO_QNAME = new QName("", "YO");
    private final static QName _XO_QNAME = new QName("", "XO");
    private final static QName _X_QNAME = new QName("", "X");
    private final static QName _External_QNAME = new QName("", "External");
    private final static QName _Y_QNAME = new QName("", "Y");
    private final static QName _Style_QNAME = new QName("", "Style");
    private final static QName _Z_QNAME = new QName("", "Z");
    private final static QName _YS_QNAME = new QName("", "YS");
    private final static QName _XS_QNAME = new QName("", "XS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gemwire.bolblox.format.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityCapabilities }
     * 
     */
    public SecurityCapabilities createSecurityCapabilities() {
        return new SecurityCapabilities();
    }

    /**
     * Create an instance of {@link Float }
     * 
     */
    public Float createFloat() {
        return new Float();
    }

    /**
     * Create an instance of {@link CFrame }
     * 
     */
    public CFrame createCFrame() {
        return new CFrame();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link SharedString }
     * 
     */
    public SharedString createSharedString() {
        return new SharedString();
    }

    /**
     * Create an instance of {@link BinaryString }
     * 
     */
    public BinaryString createBinaryString() {
        return new BinaryString();
    }

    /**
     * Create an instance of {@link Color3 }
     * 
     */
    public Color3 createColor3() {
        return new Color3();
    }

    /**
     * Create an instance of {@link Color3Uint8 }
     * 
     */
    public Color3Uint8 createColor3Uint8() {
        return new Color3Uint8();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Null }
     * 
     */
    public Null createNull() {
        return new Null();
    }

    /**
     * Create an instance of {@link CoordinateFrame }
     * 
     */
    public CoordinateFrame createCoordinateFrame() {
        return new CoordinateFrame();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link Family }
     * 
     */
    public Family createFamily() {
        return new Family();
    }

    /**
     * Create an instance of {@link CachedFaceId }
     * 
     */
    public CachedFaceId createCachedFaceId() {
        return new CachedFaceId();
    }

    /**
     * Create an instance of {@link NumberRange }
     * 
     */
    public NumberRange createNumberRange() {
        return new NumberRange();
    }

    /**
     * Create an instance of {@link PhysicalProperties }
     * 
     */
    public PhysicalProperties createPhysicalProperties() {
        return new PhysicalProperties();
    }

    /**
     * Create an instance of {@link ProtectedString }
     * 
     */
    public ProtectedString createProtectedString() {
        return new ProtectedString();
    }

    /**
     * Create an instance of {@link Rect2D }
     * 
     */
    public Rect2D createRect2D() {
        return new Rect2D();
    }

    /**
     * Create an instance of {@link Min }
     * 
     */
    public Min createMin() {
        return new Min();
    }

    /**
     * Create an instance of {@link Max }
     * 
     */
    public Max createMax() {
        return new Max();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link UDim2 }
     * 
     */
    public UDim2 createUDim2() {
        return new UDim2();
    }

    /**
     * Create an instance of {@link UniqueId }
     * 
     */
    public UniqueId createUniqueId() {
        return new UniqueId();
    }

    /**
     * Create an instance of {@link Vector2 }
     * 
     */
    public Vector2 createVector2() {
        return new Vector2();
    }

    /**
     * Create an instance of {@link Vector3 }
     * 
     */
    public Vector3 createVector3() {
        return new Vector3();
    }

    /**
     * Create an instance of {@link Bool }
     * 
     */
    public Bool createBool() {
        return new Bool();
    }

    /**
     * Create an instance of {@link Double }
     * 
     */
    public Double createDouble() {
        return new Double();
    }

    /**
     * Create an instance of {@link Int }
     * 
     */
    public Int createInt() {
        return new Int();
    }

    /**
     * Create an instance of {@link Int64 }
     * 
     */
    public Int64 createInt64() {
        return new Int64();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link OptionalCoordinateFrame }
     * 
     */
    public OptionalCoordinateFrame createOptionalCoordinateFrame() {
        return new OptionalCoordinateFrame();
    }

    /**
     * Create an instance of {@link Roblox }
     * 
     */
    public Roblox createRoblox() {
        return new Roblox();
    }

    /**
     * Create an instance of {@link SharedStrings }
     * 
     */
    public SharedStrings createSharedStrings() {
        return new SharedStrings();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "B")
    public JAXBElement<BigDecimal> createB(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_B_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomPhysics")
    public JAXBElement<Boolean> createCustomPhysics(Boolean value) {
        return new JAXBElement<Boolean>(_CustomPhysics_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G")
    public JAXBElement<BigDecimal> createG(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_G_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<java.lang.String> createUrl(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Url_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Weight")
    public JAXBElement<BigInteger> createWeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Weight_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R10")
    public JAXBElement<java.lang.Double> createR10(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R10_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R21")
    public JAXBElement<java.lang.Double> createR21(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R21_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R20")
    public JAXBElement<java.lang.Double> createR20(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R20_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R01")
    public JAXBElement<java.lang.Double> createR01(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R01_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R12")
    public JAXBElement<java.lang.Double> createR12(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R12_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R")
    public JAXBElement<BigDecimal> createR(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_R_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R00")
    public JAXBElement<java.lang.Double> createR00(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R00_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R11")
    public JAXBElement<java.lang.Double> createR11(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R11_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R22")
    public JAXBElement<java.lang.Double> createR22(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R22_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "R02")
    public JAXBElement<java.lang.Double> createR02(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_R02_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YO")
    public JAXBElement<BigInteger> createYO(BigInteger value) {
        return new JAXBElement<BigInteger>(_YO_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XO")
    public JAXBElement<BigInteger> createXO(BigInteger value) {
        return new JAXBElement<BigInteger>(_XO_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "X")
    public JAXBElement<java.lang.Double> createX(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_X_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "External")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createExternal(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_External_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Y")
    public JAXBElement<java.lang.Double> createY(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_Y_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<java.lang.String> createStyle(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Style_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Z")
    public JAXBElement<java.lang.Double> createZ(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_Z_QNAME, java.lang.Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YS")
    public JAXBElement<BigDecimal> createYS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_YS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XS")
    public JAXBElement<java.lang.Double> createXS(java.lang.Double value) {
        return new JAXBElement<java.lang.Double>(_XS_QNAME, java.lang.Double.class, null, value);
    }

}
