//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.14 at 02:13:19 AM BST 
//


package uk.gemwire.bolblox.format.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}SharedString"/>
 *           &lt;element ref="{}BinaryString"/>
 *           &lt;element ref="{}Color3"/>
 *           &lt;element ref="{}Color3uint8"/>
 *           &lt;element ref="{}Content"/>
 *           &lt;element ref="{}CoordinateFrame"/>
 *           &lt;element ref="{}Font"/>
 *           &lt;element ref="{}NumberRange"/>
 *           &lt;element ref="{}PhysicalProperties"/>
 *           &lt;element ref="{}ProtectedString"/>
 *           &lt;element ref="{}Rect2D"/>
 *           &lt;element ref="{}Ref"/>
 *           &lt;element ref="{}SecurityCapabilities"/>
 *           &lt;element ref="{}UDim2"/>
 *           &lt;element ref="{}UniqueId"/>
 *           &lt;element ref="{}Vector2"/>
 *           &lt;element ref="{}Vector3"/>
 *           &lt;element ref="{}bool"/>
 *           &lt;element ref="{}double"/>
 *           &lt;element ref="{}float"/>
 *           &lt;element ref="{}int"/>
 *           &lt;element ref="{}int64"/>
 *           &lt;element ref="{}string"/>
 *           &lt;element ref="{}token"/>
 *         &lt;/choice>
 *         &lt;element ref="{}OptionalCoordinateFrame" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sharedStringOrBinaryStringOrColor3",
    "optionalCoordinateFrame"
})
@XmlRootElement(name = "Properties")
public class Properties {

    @XmlElements({
        @XmlElement(name = "SharedString", type = SharedString.class),
        @XmlElement(name = "BinaryString", type = BinaryString.class),
        @XmlElement(name = "Color3", type = Color3 .class),
        @XmlElement(name = "Color3uint8", type = Color3Uint8 .class),
        @XmlElement(name = "Content", type = Content.class),
        @XmlElement(name = "CoordinateFrame", type = CoordinateFrame.class),
        @XmlElement(name = "Font", type = Font.class),
        @XmlElement(name = "NumberRange", type = NumberRange.class),
        @XmlElement(name = "PhysicalProperties", type = PhysicalProperties.class),
        @XmlElement(name = "ProtectedString", type = ProtectedString.class),
        @XmlElement(name = "Rect2D", type = Rect2D.class),
        @XmlElement(name = "Ref", type = Ref.class),
        @XmlElement(name = "SecurityCapabilities", type = SecurityCapabilities.class),
        @XmlElement(name = "UDim2", type = UDim2 .class),
        @XmlElement(name = "UniqueId", type = UniqueId.class),
        @XmlElement(name = "Vector2", type = Vector2 .class),
        @XmlElement(name = "Vector3", type = Vector3 .class),
        @XmlElement(name = "bool", type = Bool.class),
        @XmlElement(name = "double", type = Double.class),
        @XmlElement(name = "float", type = Float.class),
        @XmlElement(name = "int", type = Int.class),
        @XmlElement(name = "int64", type = Int64 .class),
        @XmlElement(name = "string", type = String.class),
        @XmlElement(name = "token", type = Token.class)
    })
    protected List<Object> sharedStringOrBinaryStringOrColor3;
    @XmlElement(name = "OptionalCoordinateFrame")
    protected OptionalCoordinateFrame optionalCoordinateFrame;

    /**
     * Gets the value of the sharedStringOrBinaryStringOrColor3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sharedStringOrBinaryStringOrColor3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSharedStringOrBinaryStringOrColor3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedString }
     * {@link BinaryString }
     * {@link Color3 }
     * {@link Color3Uint8 }
     * {@link Content }
     * {@link CoordinateFrame }
     * {@link Font }
     * {@link NumberRange }
     * {@link PhysicalProperties }
     * {@link ProtectedString }
     * {@link Rect2D }
     * {@link Ref }
     * {@link SecurityCapabilities }
     * {@link UDim2 }
     * {@link UniqueId }
     * {@link Vector2 }
     * {@link Vector3 }
     * {@link Bool }
     * {@link Double }
     * {@link Float }
     * {@link Int }
     * {@link Int64 }
     * {@link String }
     * {@link Token }
     * 
     * 
     */
    public List<Object> getSharedStringOrBinaryStringOrColor3() {
        if (sharedStringOrBinaryStringOrColor3 == null) {
            sharedStringOrBinaryStringOrColor3 = new ArrayList<Object>();
        }
        return this.sharedStringOrBinaryStringOrColor3;
    }

    /**
     * Gets the value of the optionalCoordinateFrame property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalCoordinateFrame }
     *     
     */
    public OptionalCoordinateFrame getOptionalCoordinateFrame() {
        return optionalCoordinateFrame;
    }

    /**
     * Sets the value of the optionalCoordinateFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalCoordinateFrame }
     *     
     */
    public void setOptionalCoordinateFrame(OptionalCoordinateFrame value) {
        this.optionalCoordinateFrame = value;
    }

}
