//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.14 at 02:13:19 AM BST 
//


package uk.gemwire.bolblox.format.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SharedString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sharedString"
})
@XmlRootElement(name = "SharedStrings")
public class SharedStrings {

    @XmlElement(name = "SharedString", required = true)
    protected SharedString sharedString;

    /**
     * Gets the value of the sharedString property.
     * 
     * @return
     *     possible object is
     *     {@link SharedString }
     *     
     */
    public SharedString getSharedString() {
        return sharedString;
    }

    /**
     * Sets the value of the sharedString property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedString }
     *     
     */
    public void setSharedString(SharedString value) {
        this.sharedString = value;
    }

}
